set_property IOSTANDARD LVCMOS33 [get_ports ENET0_GMII_RX_CLK_0]
set_property IOSTANDARD LVCMOS33 [get_ports ENET0_GMII_RX_DV_0]
set_property IOSTANDARD LVCMOS33 [get_ports ENET0_GMII_TX_CLK_0]
set_property IOSTANDARD LVCMOS33 [get_ports ETH_RESET]
set_property PACKAGE_PIN K17 [get_ports ENET0_GMII_RX_CLK_0]
set_property PACKAGE_PIN K18 [get_ports ENET0_GMII_RX_DV_0]
set_property PACKAGE_PIN L14 [get_ports ENET0_GMII_TX_CLK_0]
set_property PACKAGE_PIN H20 [get_ports ETH_RESET]
set_property PACKAGE_PIN G14 [get_ports MDIO_ETHERNET_0_0_mdc]
set_property PACKAGE_PIN J15 [get_ports MDIO_ETHERNET_0_0_mdio_io]
set_property IOSTANDARD LVCMOS33 [get_ports MDIO_ETHERNET_0_0_mdc]
set_property IOSTANDARD LVCMOS33 [get_ports MDIO_ETHERNET_0_0_mdio_io]
set_property PACKAGE_PIN N16 [get_ports {ENET0_GMII_TX_EN_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ENET0_GMII_TX_EN_0[0]}]
set_property PACKAGE_PIN M17 [get_ports {ENET0_GMII_RXD[3]}]
set_property PACKAGE_PIN M18 [get_ports {ENET0_GMII_RXD[2]}]
set_property PACKAGE_PIN K14 [get_ports {ENET0_GMII_RXD[1]}]
set_property PACKAGE_PIN J14 [get_ports {ENET0_GMII_RXD[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ENET0_GMII_RXD[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ENET0_GMII_RXD[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ENET0_GMII_RXD[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ENET0_GMII_RXD[0]}]
set_property PACKAGE_PIN N15 [get_ports {ENET0_GMII_TXD[3]}]
set_property PACKAGE_PIN M15 [get_ports {ENET0_GMII_TXD[2]}]
set_property PACKAGE_PIN L15 [get_ports {ENET0_GMII_TXD[1]}]
set_property PACKAGE_PIN M14 [get_ports {ENET0_GMII_TXD[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ENET0_GMII_TXD[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ENET0_GMII_TXD[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ENET0_GMII_TXD[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ENET0_GMII_TXD[0]}]

set_property SLEW FAST [get_ports ETH_RESET]
set_property SLEW FAST [get_ports MDIO_ETHERNET_0_0_mdc]
set_property SLEW FAST [get_ports MDIO_ETHERNET_0_0_mdio_io]
set_property SLEW FAST [get_ports {ENET0_GMII_TXD[3]}]
set_property SLEW FAST [get_ports {ENET0_GMII_TXD[2]}]
set_property SLEW FAST [get_ports {ENET0_GMII_TXD[1]}]
set_property SLEW FAST [get_ports {ENET0_GMII_TXD[0]}]
set_property SLEW FAST [get_ports {ENET0_GMII_TX_EN_0[0]}]

set_property PACKAGE_PIN U18 [get_ports TMDS_0_clk_p]
set_property PACKAGE_PIN U19 [get_ports TMDS_0_clk_n]
set_property PACKAGE_PIN V20 [get_ports {TMDS_0_data_p[0]}]
set_property PACKAGE_PIN T20 [get_ports {TMDS_0_data_p[1]}]
set_property PACKAGE_PIN N20 [get_ports {TMDS_0_data_p[2]}]
set_property PACKAGE_PIN W20 [get_ports {TMDS_0_data_n[0]}]
set_property PACKAGE_PIN U20 [get_ports {TMDS_0_data_n[1]}]
set_property PACKAGE_PIN P20 [get_ports {TMDS_0_data_n[2]}]

set_property PACKAGE_PIN R19 [get_ports {IIC_0_0_scl_io}]
set_property PACKAGE_PIN T19 [get_ports {IIC_0_0_sda_io}]
set_property IOSTANDARD LVCMOS33 [get_ports {IIC_0_0_scl_io}]
set_property IOSTANDARD LVCMOS33 [get_ports {IIC_0_0_sda_io}]

set_property IOSTANDARD LVCMOS33 [get_ports {EMIO_GPIO_tri_io[0]}]
set_property PACKAGE_PIN P15 [get_ports {EMIO_GPIO_tri_io[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {EMIO_GPIO_tri_io[1]}]
set_property PACKAGE_PIN P16 [get_ports {EMIO_GPIO_tri_io[1]}]

set_property IOSTANDARD LVCMOS33 [get_ports {AXI_GPIO_tri_io[0]}]
set_property PACKAGE_PIN U12 [get_ports {AXI_GPIO_tri_io[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AXI_GPIO_tri_io[1]}]
set_property PACKAGE_PIN T12 [get_ports {AXI_GPIO_tri_io[1]}]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets ENET0_GMII_TX_CLK_0_IBUF]